namespace: k8s-microservices
name: user-manager-api
app:
  replicas: 1
  containerPort: 8080
  image:
    repository: raihanorium/user-manager-api
    tag: 0.0.0-local
  database:
    host: user-manager-api-db
    port: 3306
    name: user_manager
    user: root
    password: root

mysql:
  nameOverride: db
  namespaceOverride: k8s-microservices
  image:
    tag: 8.4.2
  auth:
    rootPassword: root
    database: user_manager