apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
spec:
  type: LoadBalancer
  selector:
    app: user-manager
  ports:
    - port: 3000
      targetPort: 3000