apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: user-manager-api
  ports:
    - port: 8080
      targetPort: 8080