apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  db_host: {{quote .Values.app.database.host }}
  db_port: {{quote  .Values.app.database.port }}
  db_name: {{quote  .Values.app.database.name }}
  db_user: {{quote  .Values.app.database.user }}
  db_password: {{quote  .Values.app.database.password }}
